version: "3.1"

services:
    web:
        image: nginx:latest
        ports:
            - 8080:80
        volumes:
            - ./src:/var/www/html
            - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
    php:
        build:
            context: .
        volumes:
            - ./src:/var/www/html
            
    mysql:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_DATABASE: 'php'
        volumes:
            - mysqldata:/var/lib/mysql
        ports:
            - 3307:3306

volumes:
    mysqldata: {}